service: discord-bot-newsletter

frameworkVersion: '3'

package:
  individually: true

provider:
  name: aws
  runtime: python3.11

functions:
  app:
    handler: app.main.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-python-requirements
